### ISSUE TITLE
Instructions are targeting a non-existent BSC version

### ISSUE THREAD

**Issue by abrinckm** [binance-chain/docs-site#252]
I am reading this page here: https://docs.binance.org/smart-chain/developer/fullnode.html

I cannot find the version v1.9.13-alpha.0 as specified in the documentation.  The only release I can find is v1.0.0-alpha.0 as seen here: https://github.com/binance-chain/bsc/tags

Is it possible that this release has not made public? Perhaps Binance-chain developers are able to see multiple releases but I cannot. If new releases are not public, when would it be possible to get hands on any new releases?

Thanks :)

**Comment by huangsuyu** [comment]
Hello, @abrinckm Thanks for your report

The version is already updated to v1.0.0-alpha.0

**Comment by abrinckm** [comment]
@huangsuyu Thanks for the clarification. I can close this issue. :)
