### ISSUE TITLE
Clarifications on dex-api and api-server endpoints serving

### ISSUE THREAD

**Issue by jun0tpyrc** [binance-chain/docs-site#349]
It seems unclear that after pulling up bnbchaind & bnbcli seems one can only serve API in 
https://docs.binance.org/api-reference/api-server.html

but not 
https://docs.binance.org/api-reference/dex-api/paths.html

Can one also prepare node / api-server to serve the dex-api?

**Comment by huangsuyu** [comment]
Hello, @jun0tpyrc 

this doc: https://docs.binance.org/api-reference/dex-api/paths.html is for HTTP APIs provided by Accelerated nodes which are a public service run by Binance chain team.
