### ISSUE TITLE
The links to the Binance testnet faucet is broken

### ISSUE THREAD

**Issue by andreipope** [binance-chain/docs-site#352]
On the [testnet page](https://docs.binance.org/guides/testnet.html) page, the link to the [testnet faucet](https://www.binance.com/en/dex/testnet/address) is broken. It looks like you changed the address, as this used to work some time ago. Can you please update this link?

P.S.: I'm not looking for the Binance Smart Chain Faucet, that's something different.

Thanks!

**Comment by testrain** [comment]
Same question, how could I get Binance chain testnet bnb?
