### ISSUE TITLE
source variable on bridge

### ISSUE THREAD

**Issue by ddsvetlov** [binance-chain/docs-site#400]
Hello everyone.

I try to use Panama bridge and have some question about api. 
When I want to use POST query to api/v2/swaps I need to fill "source" variable. 
So testing query to transfer USDT from Ethereum Mainnet to BSC give me value "source": 921.
When I can find all values of source to use api? 

Thanks a lot.

**Comment by alesl** [comment]
@ddsvetlov did you ever find out what the value should be?

**Comment by MarekSykokora** [comment]
Dobrý den nerozumím proč mi píšete samozřejmě mám přehled o svém účtu. 

Odesláno z iPadu
