### ISSUE TITLE
Ledger Wallet documentation confusing

### ISSUE THREAD

**Issue by B-Souty** [binance-chain/docs-site#406]
Hi,

In the Ledger Wallet documentation it says to search for the `Ethereum` app, then locate `Binance Chain` and install. The screenshot provided shows the `Ethereum` app.

It is confusing because both `Ethereum` and `Binance Chain` exist on Ledger.

c.f. https://github.com/binance-chain/docs-site/blame/master/docs/smart-chain/wallet/ledger.md#L20

**Comment by huangsuyu** [comment]
Hello, @B-Souty. Binance Chain is a dual chain system. 

You use  `Binance Chain` app for Binance chain and `Ethereum` app for Binance Smart Chain.

**Comment by B-Souty** [comment]
Hi @huangsuyu, thanks for the clarification. However the confusion remain in the documentation. Considering this is a doc for Binance Smart Chain, I don't think the `Binance Chain` app should be mentioned there.

**Comment by samuelpj** [comment]
Hello @B-Souty ,  you are correct. The documentation for using ledger with BSC should not mention the Binance Chain ledger application at all. This is confusing and should be updated. I came here to notify of the same issue.
