### ISSUE TITLE
Gnosis Safe contract addresses

### ISSUE THREAD

**Issue by yosriady** [binance-chain/docs-site#463]
On https://docs.binance.org/smart-chain/developer/gnosis.html, can we get the list of deployed Safe contract addresses?

Specifically:

- `GnosisSafe` master copy contract
- `GnosisSafeProxyFactory`
- `Multisend` if one is deployed

**Comment by huangsuyu** [comment]
GnosisSafeProxyFactory:
https://bscscan.com/tx/0x73481bbd5a80aa4510869877aa385be63d32b80a2931c663f137604840646e62

GnosisSafe
https://bscscan.com/address/0x2bb001433cf04c1f7d71e3c40fed66b2b563065e#code

MultiSend
https://bscscan.com/address/0x663a65a0523103846a1761ab90a1a4731156c453

**Comment by MarekSykokora** [comment]
please TXID Token balance Address 0xb8c77482e45f1f44de1745f52c74426c631bdd52 Contract address 0xB8c77482e45F1F44dE1745F52C74426C631bDD52 infura Balance: 23507.131066435489362031 BNB Value: 3338.012611433839 ETH (@ 0,142 / Eth) Decimal: 18 on bnb136ns6lfw4zs5hg4n85vdthaad7hq5m4gtkgf23 Please for privacy is a large amount. Please help If you encounter a problem, I must have everything in order Thank you Marek Sýkora, please answer sykora.marek74@icloud.com sykoramarek@gmail.com don't be angry that I don't write in public Thank you Marek Sýkora
